language: node_js
node_js:
  - "6"
before_install:
  - gem install sass
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - export NODE_ENV=production
  - ./scripts/plug_versions
  - ./scripts/get_boards production
  - ./configure production
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - ./ninja && ./scripts/deploy
