language: node_js
node_js:
  - "12"
addons:
  apt:
    sources:
      - sourceline: 'ppa:js-reynaud/kicad-5.1'
    packages:
      - inkscape
      - kicad
      - xvfb
script:
  - bash keep_alive.sh &
  - export NODE_ENV=production
  - ./scripts/plug_versions
  - ./scripts/get_boards production $CACHED_BUILD
  - ./configure production $CACHED_BUILD
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - if  [ "${CACHED_BUILD}" != "cached" ]; then ./ninja clean; fi
  - Xvfb :0 -screen 0 1024x768x24 > X.log 2>&1 &
  - export DISPLAY=:0
  - ./ninja -j 2 && cp registry.json build/ && ./scripts/deploy
cache:
  yarn: true
  directories:
    - ./build
env:
  - CACHED_BUILD=false
