language: node_js
node_js:
  - "12"
addons:
  apt:
    sources:
      - sourceline: 'ppa:js-reynaud/kicad-5.1'
    packages:
      - inkscape
      - kicad
      - xvfb
services:
  - xvfb
script:
  - bash keep_alive.sh &
  - export NODE_ENV=production
  - ./scripts/plug_versions
  - ./scripts/get_boards production $CACHED_BUILD
  - if  [ "${CACHED_BUILD}" == "cached" ] && [ -f "build/.temp/boards.json" ]; then mv build/.temp/boards.json previous-boards.json; fi
  - if test -f previous-boards.json; then echo "$(cat previous-boards.json)"; fi
  - ./configure production $CACHED_BUILD
  - wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip ninja-linux.zip
  - if  [ "${CACHED_BUILD}" != "cached" ]; then ./ninja clean; fi
  - ./ninja -j 2 && cp registry.json build/
  - echo "$(cat build/.temp/boards.json)"
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then yarn smoke-test && ./scripts/deploy; fi
cache:
  yarn: true
  directories:
    - ./build
    # needed to cache folder with Cypress binary
    - ~/.cache
